language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies
script:
  - make venv
  - source venv/bin/activate
  - make test
branches:
  only:
    - master
after_success:
  codecov